// frontend/src/components/TunnelCommandForm.tsx
import {
  useId,
  useMemo,
  useState,
  type KeyboardEvent,
} from "react";
import { Check, Copy, RefreshCw, X } from "lucide-react";
import { Input } from "@/components/ui/input";
import type { Lease } from "@/types/api";
import { cn } from "@/lib/utils";
import {
  buildTunnelPreviewURL,
  buildServiceStatusHostname,
  normalizeAbsoluteHTTPURL,
  type TunnelCommandOS,
} from "@/lib/tunnelCommand";
import {
  DEFAULT_HOST,
  readCurrentOrigin,
  useTunnelCommand,
} from "@/hooks/useTunnelCommand";
import type { ShareKind } from "@/lib/shareLink";

const SHARE_KIND_LABEL: Record<ShareKind, string> = {
  url: "URL",
  file: "File",
  port: "Port",
};

const SHARE_PLACEHOLDER = "file:///Users/me/site/index.html or 3000";

type TunnelCommandFormProps = {
  className?: string;
  theme?: "light" | "terminal";
} & (
  | { mode: "hero"; leases: Lease[] | null }
  | { mode?: "full"; leases?: never }
);

type ServiceStatus = "waiting" | "registered" | "alive";

export function TunnelCommandForm({
  className,
  theme = "light",
  mode,
  leases,
}: TunnelCommandFormProps) {
  if (mode === "hero") {
    return (
      <HeroTunnelCommandForm
        className={className}
        theme={theme}
        leases={leases}
      />
    );
  }

  return (
    <FullTunnelCommandForm
      className={className}
      theme={theme}
    />
  );
}

function HeroTunnelCommandForm({
  className,
  theme,
  leases,
}: Required<Pick<TunnelCommandFormProps, "theme">> &
  Pick<TunnelCommandFormProps, "className"> & {
    leases: Lease[] | null;
  }) {
  const isTerminal = theme === "terminal";
  const [tunnelTarget, setTunnelTarget] = useState<TunnelCommandOS>("unix");
  const {
    currentOrigin,
    nameSeed,
    target,
    setTarget,
    copied,
    os,
    generatedName,
    effectiveName,
    shareKind,
    installBlock,
    runBlock,
    handleCopy,
    handleNameChange,
    handleShuffleName,
  } = useTunnelCommand({
    os: tunnelTarget,
  });

  const previewURL = useMemo(
    () => buildTunnelPreviewURL(currentOrigin, effectiveName, target, nameSeed),
    [currentOrigin, effectiveName, nameSeed, target]
  );
  const statusHostname = useMemo(
    () =>
      buildServiceStatusHostname(currentOrigin, effectiveName, target, nameSeed),
    [currentOrigin, effectiveName, nameSeed, target]
  );

  const lease = statusHostname === "" ? undefined : leases?.find(
    (candidate) => candidate.hostname.trim().toLowerCase() === statusHostname
  );
  const serviceStatus: ServiceStatus = !lease
    ? "waiting"
    : lease.ready > 0 ? "alive" : "registered";

  const serviceStatusTone = {
    alive: isTerminal ? "bg-green-400" : "bg-green-600",
    registered: isTerminal ? "bg-sky-400" : "bg-sky-600",
    waiting: isTerminal ? "bg-slate-500" : "bg-slate-400",
  }[serviceStatus];
  const serviceStatusHeadline = {
    alive: "This URL is live now",
    registered: "URL reserved",
    waiting: "Waiting for Connection",
  }[serviceStatus];
  const isPreviewURLDisabled = serviceStatus === "waiting";
  const heroSectionLabelClass = cn(
    "text-[13px] font-semibold tracking-normal sm:text-sm",
    isTerminal ? "text-slate-100" : "text-foreground/85"
  );
  const heroURLClass = cn(
    "block overflow-x-auto whitespace-nowrap font-mono text-[15px] font-medium sm:text-base",
    isTerminal ? "text-sky-300" : "text-primary"
  );
  const platformButtonGroupClass = cn(
    "flex shrink-0 rounded-md border p-0.5",
    isTerminal
      ? "border-white/6 bg-white/[0.035]"
      : "border-border bg-border"
  );
  const platformButtonClass = (selected: boolean) =>
    cn(
      "min-w-[72px] whitespace-nowrap rounded-sm px-2.5 py-1.5 text-[11px] font-semibold transition-colors",
      selected
        ? isTerminal
          ? "bg-white/[0.08] text-slate-200"
          : "bg-background text-foreground/85"
        : isTerminal
          ? "text-slate-500 hover:text-slate-300"
          : "text-text-muted hover:text-foreground"
    );
  const heroControlLabelClass = cn(
    "shrink-0 text-[9px] font-semibold uppercase tracking-normal",
    isTerminal ? "text-slate-500" : "text-text-muted"
  );
  const heroExampleClass = cn(
    "mx-1 font-mono",
    isTerminal ? "text-slate-200" : "text-foreground"
  );
  const heroControlInputClass = cn(
    "h-auto border-0 bg-transparent px-0 py-0 text-[13px] shadow-none focus-visible:ring-0",
    isTerminal
      ? "text-slate-200 placeholder:text-slate-600"
      : "text-foreground/85 placeholder:text-muted-foreground"
  );
  const heroShuffleButtonClass = cn(
    "inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-sm transition-colors",
    isTerminal
      ? "text-slate-500 hover:bg-white/[0.06] hover:text-slate-200"
      : "text-text-muted hover:bg-foreground/5 hover:text-foreground"
  );
  return (
    <div className={cn("space-y-5", className)}>
      <div className="space-y-2">
        <div className="space-y-1.5">
          <p className={heroSectionLabelClass}>
            1. Paste what you want to share
          </p>
          <p
            className={cn(
              "text-[12px] leading-5",
              isTerminal ? "text-slate-400" : "text-text-muted"
            )}
          >
            A local port such as
            <span className={heroExampleClass}>3000</span>, a running URL such as
            <span className={heroExampleClass}>http://localhost:3000</span>, or a
            file path such as
            <span className={heroExampleClass}>
              file:///Users/me/site/index.html
            </span>
            — file paths are served as a static site straight from that folder,
            so nothing needs to be running locally.
          </p>
        </div>
      </div>

      <div className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <p className={heroSectionLabelClass}>2. Run this command</p>
          <div className={platformButtonGroupClass}>
            <button
              type="button"
              onClick={() => setTunnelTarget("unix")}
              className={platformButtonClass(os === "unix")}
            >
              Linux
            </button>
            <button
              type="button"
              onClick={() => setTunnelTarget("windows")}
              className={platformButtonClass(os === "windows")}
            >
              Windows
            </button>
          </div>
        </div>
        <div className="space-y-2">
          <div className="flex min-w-0 items-center gap-2">
            <span className={heroControlLabelClass}>Share</span>
            <Input
              type="text"
              value={target}
              onChange={(event) => setTarget(event.target.value)}
              placeholder={SHARE_PLACEHOLDER}
              aria-label="Link, file path, or local port to share"
              className={cn(heroControlInputClass, "min-w-0 flex-1 font-mono")}
            />
            {target.trim() !== "" && (
              <span
                className={cn(
                  "shrink-0 rounded px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-normal",
                  isTerminal
                    ? "bg-white/8 text-slate-400"
                    : "bg-muted text-text-muted"
                )}
                title="Detected share type"
              >
                {SHARE_KIND_LABEL[shareKind]}
              </span>
            )}
          </div>
          <div className="flex min-w-0 items-center gap-2">
            <span className={heroControlLabelClass}>Name</span>
            <Input
              type="text"
              onChange={handleNameChange}
              placeholder={generatedName}
              aria-label="Public name"
              className={cn(heroControlInputClass, "min-w-0 flex-1")}
            />
            <button
              type="button"
              onClick={handleShuffleName}
              className={heroShuffleButtonClass}
              aria-label="Shuffle public name"
              title="Shuffle public name"
            >
              <RefreshCw className="h-4 w-4" aria-hidden="true" />
            </button>
          </div>
        </div>
        <div
          className={cn(
            "relative min-h-37 rounded-lg border px-4 py-4 pr-14 font-mono text-sm leading-7",
            isTerminal
              ? "border-white/10 bg-black/55 text-white shadow-[inset_0_1px_0_rgba(255,255,255,0.05)]"
              : "border-border/80 bg-border/90 text-foreground"
          )}
        >
          <button
            type="button"
            onClick={handleCopy}
            className={cn(
              "absolute top-4 right-4 inline-flex h-8 w-8 items-center justify-center rounded-md transition-colors",
              isTerminal
                ? "text-emerald-300/75 hover:bg-emerald-400/10 hover:text-emerald-200"
                : "text-emerald-600 hover:bg-emerald-500/10 hover:text-emerald-700"
            )}
            aria-label="Copy command"
            title={copied ? "Copied" : "Copy"}
          >
            {copied ? (
              <Check className="h-4 w-4" />
            ) : (
              <Copy className="h-4 w-4" />
            )}
          </button>
          <pre className="overflow-x-auto whitespace-pre-wrap break-all">
            <span className="block">{installBlock}</span>
            <span className="mt-2 block">{runBlock}</span>
          </pre>
        </div>
      </div>

      <div className="space-y-2 pt-1">
        <p className={heroSectionLabelClass}>3. Open this public URL</p>
        <div
          className={cn(
            "space-y-3 rounded-lg border px-3.5 py-3",
            isTerminal
              ? "border-white/8 bg-white/4.5"
              : "border-border bg-white"
          )}
        >
          <div
            className={cn(
              "flex items-center gap-2 text-[13px] font-semibold",
              isTerminal ? "text-slate-300" : "text-foreground"
            )}
          >
            <span
              className={cn("h-2 w-2 rounded-full", serviceStatusTone)}
              aria-hidden="true"
            />
            <span>{serviceStatusHeadline}</span>
          </div>
          {isPreviewURLDisabled ? (
            <span
              aria-disabled="true"
              className={cn(heroURLClass, "cursor-not-allowed opacity-70")}
            >
              {previewURL}
            </span>
          ) : (
            <a
              href={previewURL}
              target="_blank"
              rel="noopener noreferrer"
              className={cn(heroURLClass, "underline-offset-4 hover:underline")}
            >
              {previewURL}
            </a>
          )}
        </div>
      </div>
    </div>
  );
}

function FullTunnelCommandForm({
  className,
  theme,
}: Required<Pick<TunnelCommandFormProps, "theme">> &
  Pick<TunnelCommandFormProps, "className">) {
  const inputId = useId();
  const isTerminal = theme === "terminal";
  const [tunnelTarget, setTunnelTarget] = useState<TunnelCommandOS>("unix");
  const currentOrigin = readCurrentOrigin();

  const [relayUrls, setRelayUrls] = useState<string[]>(() => [
    currentOrigin,
  ]);
  const [discoveryEnabled, setDiscoveryEnabled] = useState(true);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [urlInput, setUrlInput] = useState("");
  const [enableUDP, setEnableUDP] = useState(false);
  const [udpPort, setUDPPort] = useState("");
  const [thumbnailURL, setThumbnailURL] = useState("");

  const normalizedThumbnailURL = useMemo(
    () => normalizeAbsoluteHTTPURL(thumbnailURL),
    [thumbnailURL]
  );
  const thumbnailError = useMemo(() => {
    if (thumbnailURL.trim() === "" || normalizedThumbnailURL !== "") {
      return "";
    }

    return "Thumbnail must be an absolute http:// or https:// URL.";
  }, [normalizedThumbnailURL, thumbnailURL]);

  const {
    target,
    setTarget,
    name,
    copied,
    os,
    generatedName,
    shareKind,
    installBlock,
    runBlock,
    handleCopy,
    handleNameChange,
  } = useTunnelCommand({
    relayUrls,
    discovery: discoveryEnabled,
    thumbnailURL: normalizedThumbnailURL,
    enableUDP,
    udpPort,
    os: tunnelTarget,
  });

  const addRelayURL = (url: string) => {
    const trimmed = url.trim();
    if (!trimmed || relayUrls.includes(trimmed)) {
      return;
    }

    try {
      new URL(trimmed);
      setRelayUrls((prev) => [...prev, trimmed]);
      setUrlInput("");
    } catch {
      // Ignore invalid relay URL input.
    }
  };

  const removeRelayURL = (url: string) => {
    if (!discoveryEnabled && relayUrls.length <= 1) {
      return;
    }
    setRelayUrls((prev) => prev.filter((candidate) => candidate !== url));
  };

  const handleURLKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter") {
      event.preventDefault();
      addRelayURL(urlInput);
      return;
    }

    if (event.key === "Backspace" && urlInput === "" && relayUrls.length > 0) {
      setRelayUrls((prev) => prev.slice(0, -1));
    }
  };
  const sectionLabelClass = isTerminal
    ? "text-sm font-medium text-slate-200"
    : "text-sm font-medium text-foreground dark:text-zinc-100";
  const helpTextClass = isTerminal
    ? "text-xs text-slate-400"
    : "text-xs leading-5 text-muted-foreground dark:text-zinc-500";
  const inlineFieldClass = isTerminal
    ? "flex items-center overflow-hidden rounded-lg border border-white/10 bg-white/5"
    : "flex items-center overflow-hidden rounded-md border border-border/80 bg-secondary/55 focus-within:border-ring focus-within:ring-1 focus-within:ring-ring/30 dark:border-white/10 dark:bg-secondary/60";
  const inlinePrefixClass = isTerminal
    ? "shrink-0 border-r border-white/10 px-3 text-xs font-medium uppercase tracking-normal text-slate-400"
    : "shrink-0 border-r border-border px-3 text-[0.82rem] font-medium uppercase tracking-normal text-text-muted dark:border-border dark:text-zinc-400";
  const inlineInputClass = isTerminal
    ? "h-10 border-0 bg-transparent px-3 text-sm text-white placeholder:text-slate-500 shadow-none focus-visible:ring-0"
    : "h-9 border-0 bg-transparent px-3 text-sm font-semibold text-foreground placeholder:text-text-muted shadow-none focus-visible:ring-0 dark:text-zinc-100 dark:placeholder:text-zinc-500";
  const relayFieldClass = isTerminal
    ? "flex min-h-12 flex-wrap items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-2.5 py-2"
    : "flex min-h-10 flex-wrap items-center gap-2 rounded-md border border-border bg-background px-2 py-2 shadow-sm focus-within:border-ring focus-within:ring-1 focus-within:ring-ring/25 dark:border-white/10 dark:bg-transparent";
  const relayChipClass = isTerminal
    ? "inline-flex items-center gap-1 rounded-md bg-white/10 px-2.5 py-1.5 text-xs font-medium text-slate-100"
    : "inline-flex items-center gap-1 rounded-md bg-secondary px-2.5 py-1 text-xs font-semibold text-secondary-foreground dark:bg-primary/14 dark:text-primary";
  const relayChipRemoveClass = isTerminal
    ? "hover:bg-white/10"
    : "text-text-muted hover:bg-background/80 dark:text-primary dark:hover:bg-black/20";
  const advancedInputClass = isTerminal
    ? "h-10 rounded-lg border-white/10 bg-white/5 text-white placeholder:text-slate-500"
    : "h-10 rounded-md border border-border bg-background text-foreground placeholder:text-muted-foreground shadow-sm dark:border-white/10 dark:bg-background dark:text-zinc-100 dark:placeholder:text-zinc-500";
  const osGroupClass = isTerminal
    ? "flex rounded-lg bg-white/8 p-1"
    : "flex rounded-md bg-border p-1 dark:bg-secondary/60";
  const osButtonClass = (selected: boolean) =>
    cn(
      "flex-1 rounded-sm px-3 py-2 text-sm font-semibold transition-colors",
      isTerminal
        ? selected
          ? "bg-white/8 text-slate-200"
          : "text-slate-400 hover:text-slate-300"
        : selected
          ? "bg-card text-foreground shadow-sm ring-1 ring-border/80 dark:bg-background dark:text-zinc-100 dark:ring-transparent"
          : "text-muted-foreground hover:text-foreground dark:text-zinc-500 dark:hover:text-zinc-300"
    );
  const commandPanelClass = isTerminal
    ? "relative rounded-lg border border-white/10 bg-black/30"
    : "relative rounded-md bg-secondary/55 shadow-sm ring-1 ring-border/70 dark:bg-secondary/60 dark:ring-transparent";
  const commandPreClass = isTerminal
    ? "overflow-x-auto whitespace-pre-wrap break-all p-4 pr-12 font-mono text-sm leading-7 text-white"
    : "overflow-x-auto whitespace-pre-wrap break-all p-3 pr-12 font-mono text-sm leading-7 text-foreground dark:text-zinc-100";

  return (
    <div className={cn("space-y-4 py-1", className)}>
      <div className="space-y-2">
        <label className={sectionLabelClass}>Platform</label>
        <div className={osGroupClass}>
          <button
            type="button"
            onClick={() => setTunnelTarget("unix")}
            className={osButtonClass(os === "unix")}
          >
            Linux / macOS
          </button>
          <button
            type="button"
            onClick={() => setTunnelTarget("windows")}
            className={osButtonClass(os === "windows")}
          >
            Windows
          </button>
        </div>
      </div>

      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <label htmlFor={`${inputId}-host`} className={sectionLabelClass}>
            Share
          </label>
          {target.trim() !== "" && (
            <span
              className={cn(
                "rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-normal",
                isTerminal
                  ? "bg-white/8 text-slate-400"
                  : "bg-muted text-text-muted"
              )}
              title="Detected share type"
            >
              {SHARE_KIND_LABEL[shareKind]}
            </span>
          )}
        </div>
        <div className={inlineFieldClass}>
          <span className={inlinePrefixClass}>SHARE=</span>
          <Input
            id={`${inputId}-host`}
            type="text"
            value={target}
            onChange={(event) => setTarget(event.target.value)}
            placeholder={SHARE_PLACEHOLDER}
            aria-label="Local port, URL, or file path to share"
            className={inlineInputClass}
          />
        </div>
        <p className={helpTextClass}>
          Paste what you want to share: a local port (3000), a running URL
          (http://localhost:3000), or a file path
          (file:///Users/me/site/index.html). File paths are served as a static
          site from that folder, so nothing needs to be running locally.
        </p>
      </div>

      <div className="space-y-2">
        <label
          htmlFor={`${inputId}-name`}
          className={sectionLabelClass}
        >
          Service Name
        </label>
        <div className={inlineFieldClass}>
          <span className={inlinePrefixClass}>NAME=</span>
          <Input
            id={`${inputId}-name`}
            type="text"
            value={name}
            onChange={handleNameChange}
            placeholder={generatedName}
            className={inlineInputClass}
          />
        </div>
        <p className={helpTextClass}>A unique identifier for your tunnel</p>
      </div>

      <div className="space-y-2">
        <label className={sectionLabelClass}>
          Relay URLs
        </label>
        <div className={relayFieldClass}>
          {relayUrls.map((url) => (
            <span
              key={url}
              className={relayChipClass}
            >
              {url}
              <button
                type="button"
                onClick={() => removeRelayURL(url)}
                className={cn(
                  "ml-1 rounded-sm p-0.5",
                  !discoveryEnabled && relayUrls.length <= 1
                    ? "cursor-not-allowed opacity-40"
                    : relayChipRemoveClass
                )}
                aria-label={`Remove ${url}`}
                disabled={!discoveryEnabled && relayUrls.length <= 1}
              >
                <X className="h-3 w-3" />
              </button>
            </span>
          ))}

          <input
            type="text"
            value={urlInput}
            onChange={(event) => setUrlInput(event.target.value)}
            onKeyDown={handleURLKeyDown}
            placeholder="Add relay URL..."
            className={cn(
              "min-w-[140px] flex-1 bg-transparent text-sm outline-none",
              isTerminal
                ? "text-white placeholder:text-slate-500"
                : "text-foreground placeholder:text-muted-foreground dark:text-zinc-100 dark:placeholder:text-zinc-500"
            )}
          />
        </div>
        <p className={helpTextClass}>
          Press Enter to add. Multiple relay servers for redundancy.
        </p>
      </div>

      <div className="space-y-2">
        <label className={sectionLabelClass}>
          Generated Command
        </label>
        <div className={commandPanelClass}>
          <pre className={commandPreClass}>
            <span className="block">{installBlock}</span>
            <span className="mt-2 block">{runBlock}</span>
          </pre>
          <button
            type="button"
            onClick={handleCopy}
            className={cn(
              "absolute right-2 top-1/2 -translate-y-1/2 rounded-md p-2 transition-colors",
              isTerminal ? "hover:bg-white/10" : "hover:bg-background/70 dark:hover:bg-black/20"
            )}
            aria-label="Copy command"
          >
            {copied ? (
              <Check className={cn("h-4 w-4", isTerminal ? "text-green-400" : "text-emerald-400")} />
            ) : (
              <Copy className={cn("h-4 w-4", isTerminal ? "text-slate-400" : "text-text-muted dark:text-zinc-500")} />
            )}
          </button>
        </div>
      </div>

      {!isTerminal && (
        <div className="pt-1">
          <button
            type="button"
            onClick={() => setShowAdvanced((current) => !current)}
            className="text-xs font-medium text-muted-foreground transition-colors hover:text-foreground dark:text-zinc-500 dark:hover:text-zinc-300"
          >
            {showAdvanced ? "Hide advanced options" : "Advanced options"}
          </button>
          {showAdvanced && (
            <div className="mt-3 space-y-4 rounded-md border border-border bg-muted/45 px-4 py-4 dark:border-white/8 dark:bg-background/70">
              <label className="flex items-center gap-2 text-sm text-foreground dark:text-zinc-300">
                <input
                  type="checkbox"
                  checked={discoveryEnabled}
                  onChange={(event) => {
                    const nextEnabled = event.target.checked;
                    setDiscoveryEnabled(nextEnabled);
                    if (!nextEnabled && relayUrls.length === 0) {
                      setRelayUrls([currentOrigin]);
                    }
                  }}
                  className="h-4 w-4"
                />
                <span>Enable relay discovery</span>
              </label>

              <div className="space-y-2">
                <label className="flex items-center gap-2 text-sm text-foreground dark:text-zinc-300">
                  <input
                    type="checkbox"
                    checked={enableUDP}
                    onChange={(event) => {
                      const nextEnabled = event.target.checked;
                      setEnableUDP(nextEnabled);
                      if (!nextEnabled) {
                        setUDPPort("");
                      }
                    }}
                    className="h-4 w-4"
                  />
                  <span>Enable UDP transport</span>
                </label>
                {enableUDP && (
                  <div className="space-y-1.5">
                    <Input
                      id={`${inputId}-udp-port`}
                      type="text"
                      value={udpPort}
                      onChange={(event) => setUDPPort(event.target.value)}
                      placeholder={target.trim() || DEFAULT_HOST}
                      className={advancedInputClass}
                    />
                    <p className={helpTextClass}>
                      Local UDP port to forward. Defaults to the same as Host.
                    </p>
                  </div>
                )}
              </div>

              <div className="space-y-2">
                <label
                  htmlFor={`${inputId}-thumbnail`}
                  className="text-sm font-medium text-foreground dark:text-zinc-300"
                >
                  Thumbnail URL
                </label>
                <Input
                  id={`${inputId}-thumbnail`}
                  type="url"
                  value={thumbnailURL}
                  onChange={(event) => setThumbnailURL(event.target.value)}
                  placeholder="https://cdn.example.com/thumb.png"
                  className={advancedInputClass}
                />
                {normalizedThumbnailURL && (
                  <div className="flex h-20 w-20 items-center justify-center overflow-hidden rounded-md border border-border bg-background dark:border-white/10 dark:bg-background">
                    <img
                      src={normalizedThumbnailURL}
                      alt="Thumbnail preview"
                      className="h-full w-full object-cover"
                    />
                  </div>
                )}
                {thumbnailError && (
                  <p className="text-xs text-destructive">{thumbnailError}</p>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// docs/src/lib/components/landing/TunnelCommandForm.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import {
		buildTunnelDisplayCommand,
		buildTunnelPreviewURL,
		RELAY_ORIGIN,
		type TunnelCommandOS
	} from '$lib/tunnel-command';
	import { buildDefaultExposeName } from '$lib/expose-name';
	import { classifyShareInput, type ShareKind } from '$lib/share-link';

	const SHARE_KIND_LABEL: Record<ShareKind, string> = { url: 'URL', file: 'File', port: 'Port' };
	const SHARE_PLACEHOLDER = 'file:///Users/me/site/index.html or 3000';

	// Empty by default so the field reads as "paste a link here" instead of
	// pre-committing the user to a local port.
	let target = $state('');
	let os: TunnelCommandOS = $state('unix');
	let name = $state('');
	let nameSeed = $state('');
	let copied = $state(false);

	onMount(() => {
		nameSeed = crypto.randomUUID();
	});

	const share = $derived(classifyShareInput(target));
	const generatedName = $derived(buildDefaultExposeName(share.seedTarget, nameSeed));
	const effectiveName = $derived(name.trim() || generatedName);

	const commandLines = $derived.by(() =>
		buildTunnelDisplayCommand({
			currentOrigin: RELAY_ORIGIN,
			target: share.target,
			name: effectiveName,
			nameSeed,
			relayUrls: [RELAY_ORIGIN],
			discovery: true,
			thumbnailURL: '',
			os,
			shareKind: share.kind,
			servePath: share.path
		}).split('\n')
	);

	// Install is the first line(s); the expose command is the rest.
	const installBlock = $derived(
		os === 'windows' ? commandLines.slice(0, 2).join('\n') : (commandLines[0] ?? '')
	);
	const runBlock = $derived(
		os === 'windows' ? commandLines.slice(2).join('\n') : commandLines.slice(1).join('\n')
	);

	const previewURL = $derived(
		buildTunnelPreviewURL(RELAY_ORIGIN, effectiveName, share.seedTarget, nameSeed)
	);

	function handleCopy() {
		const fullCommand = installBlock + '\n' + runBlock;
		navigator.clipboard.writeText(fullCommand).then(() => {
			copied = true;
			setTimeout(() => {
				copied = false;
			}, 2000);
		});
	}

	function handleShuffleName() {
		nameSeed = crypto.randomUUID();
		name = '';
	}

	function handleNameChange(event: Event) {
		name = (event.target as HTMLInputElement).value;
	}
</script>

<div id="quick-start" class="relative mt-8 scroll-mt-24 sm:mt-10">
	<div class="mx-auto w-full max-w-6xl text-left">
		<div class="space-y-2">
			<p
				class="text-sm font-semibold uppercase tracking-[0.3em]"
				style="color: var(--neon-cyan);"
			>
				Quick Start
			</p>
			<h2
				class="text-3xl font-semibold tracking-tight"
				style="color: var(--foreground);"
			>
				Expose service
			</h2>
		</div>

		<div
			class="relative mx-auto mt-4 w-full max-w-[520px] rounded-xl border px-4 py-5 sm:px-5 sm:py-6"
			style="background: var(--hero-terminal-bg); border-color: var(--hero-terminal-border); color: var(--hero-terminal-foreground); box-shadow: 0 30px 72px var(--hero-terminal-shadow);"
		>
			<div class="mb-5 flex min-w-0 items-center gap-3">
				<span
					aria-hidden="true"
					class="shrink-0 font-mono text-lg leading-none"
					style="color: var(--hero-terminal-accent);"
				>
					{'>'}
				</span>
				<h3
					id="tunnel-preview"
					class="min-w-0 text-xl font-bold tracking-tight sm:text-2xl"
				>
					Run this command
				</h3>
			</div>

			<div class="space-y-5">
				<!-- 1. Paste what you want to share -->
				<div class="space-y-2">
					<div class="space-y-1.5">
						<p class="text-[13px] font-semibold tracking-[0.04em] text-slate-100 sm:text-sm">
							1. Paste what you want to share
						</p>
						<p class="text-[12px] leading-5 text-slate-400">
							A local port such as
							<span class="mx-1 font-mono text-slate-200">3000</span>, a running URL
							such as
							<span class="mx-1 font-mono text-slate-200">http://localhost:3000</span>,
							or a file path such as
							<span class="mx-1 font-mono text-slate-200"
								>file:///Users/me/site/index.html</span
							>
							— file paths are served as a static site straight from that folder, so
							nothing needs to be running locally.
						</p>
					</div>
				</div>

				<!-- 2. Run this command -->
				<div class="space-y-3">
					<div class="flex flex-wrap items-center justify-between gap-3">
						<p class="text-[13px] font-semibold tracking-[0.04em] text-slate-100 sm:text-sm">
							2. Run this command
						</p>
						<div
							class="flex shrink-0 rounded-lg border p-0.5"
							style="border-color: rgba(255,255,255,0.06); background: rgba(255,255,255,0.035);"
						>
							<button
								type="button"
								onclick={() => {
									os = 'unix';
								}}
								class="min-w-[72px] whitespace-nowrap rounded-md px-2.5 py-1.5 text-[11px] font-semibold transition-colors {os ===
								'unix'
									? 'bg-white/[0.08] text-slate-200'
									: 'text-slate-500 hover:text-slate-300'}"
							>
								Linux
							</button>
							<button
								type="button"
								onclick={() => {
									os = 'windows';
								}}
								class="min-w-[72px] whitespace-nowrap rounded-md px-2.5 py-1.5 text-[11px] font-semibold transition-colors {os ===
								'windows'
									? 'bg-white/[0.08] text-slate-200'
									: 'text-slate-500 hover:text-slate-300'}"
							>
								Windows
							</button>
						</div>
					</div>

					<!-- Share + Name controls -->
					<div class="space-y-2">
						<div class="flex min-w-0 items-center gap-2">
							<span
								class="shrink-0 text-[9px] font-semibold uppercase tracking-[0.16em] text-slate-500"
							>
								Share
							</span>
							<input
								type="text"
								bind:value={target}
								placeholder={SHARE_PLACEHOLDER}
								aria-label="Link, file path, or local port to share"
								class="h-auto min-w-0 flex-1 border-0 bg-transparent px-0 py-0 font-mono text-[13px] text-slate-200 shadow-none outline-none placeholder:text-slate-600"
							/>
							{#if target.trim() !== ''}
								<span
									class="shrink-0 rounded px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-400"
									style="background: rgba(255,255,255,0.06);"
									title="Detected share type"
								>
									{SHARE_KIND_LABEL[share.kind]}
								</span>
							{/if}
						</div>
						<div class="flex min-w-0 items-center gap-2">
							<span
								class="shrink-0 text-[9px] font-semibold uppercase tracking-[0.16em] text-slate-500"
							>
								Name
							</span>
							<input
								type="text"
								oninput={handleNameChange}
								placeholder={generatedName}
								aria-label="Public name"
								class="min-w-0 flex-1 border-0 bg-transparent px-0 py-0 text-[13px] text-slate-200 shadow-none outline-none placeholder:text-slate-600"
							/>
							<button
								type="button"
								onclick={handleShuffleName}
								class="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-slate-500 transition-colors hover:bg-white/[0.06] hover:text-slate-200"
								aria-label="Shuffle public name"
								title="Shuffle public name"
							>
								<svg
									class="h-4 w-4"
									fill="none"
									viewBox="0 0 24 24"
									stroke="currentColor"
									stroke-width="2"
									stroke-linecap="round"
									stroke-linejoin="round"
								>
									<polyline points="23 4 23 10 17 10" />
									<polyline points="1 20 1 14 7 14" />
									<path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10" />
									<path d="M20.49 15a9 9 0 0 1-14.85 3.36L1 14" />
								</svg>
							</button>
						</div>
					</div>

					<!-- Command block -->
					<div
						class="relative min-h-[148px] rounded-xl border px-4 py-4 pr-14 font-mono text-sm leading-7"
						style="border-color: rgba(255,255,255,0.1); background: rgba(0,0,0,0.55); color: white; box-shadow: inset 0 1px 0 rgba(255,255,255,0.05);"
					>
						<button
							type="button"
							onclick={handleCopy}
							class="absolute right-4 top-4 inline-flex h-8 w-8 items-center justify-center rounded-lg transition-colors hover:bg-emerald-400/10"
							style="color: rgba(110,231,183,0.75);"
							aria-label="Copy command"
							title={copied ? 'Copied' : 'Copy'}
						>
							{#if copied}
								<svg
									class="h-4 w-4"
									fill="none"
									viewBox="0 0 24 24"
									stroke="currentColor"
									stroke-width="2"
									stroke-linecap="round"
									stroke-linejoin="round"
								>
									<polyline points="20 6 9 17 4 12" />
								</svg>
							{:else}
								<svg
									class="h-4 w-4"
									fill="none"
									viewBox="0 0 24 24"
									stroke="currentColor"
									stroke-width="2"
									stroke-linecap="round"
									stroke-linejoin="round"
								>
									<rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
									<path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
								</svg>
							{/if}
						</button>
						<pre class="overflow-x-auto whitespace-pre-wrap break-all"><span class="block">{installBlock}</span><span class="mt-2 block">{runBlock}</span></pre>
					</div>
				</div>

				<!-- 3. Open this public URL -->
				<div class="space-y-2 pt-1">
					<p class="text-[13px] font-semibold tracking-[0.04em] text-slate-100 sm:text-sm">
						3. Open this public URL
					</p>
					<div
						class="space-y-3 rounded-xl border px-3.5 py-3"
						style="border-color: rgba(255,255,255,0.08); background: rgba(255,255,255,0.045);"
					>
						<a
							href={previewURL}
							target="_blank"
							rel="noopener noreferrer"
							class="block overflow-x-auto whitespace-nowrap font-mono text-[15px] font-medium text-sky-300 underline-offset-4 hover:underline sm:text-base"
						>
							{previewURL}
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
